# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.1
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: enjoliver_testing

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "enjoliver-api/tox.ini" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo pip install tox
      - save_cache:
          paths:
            - enjoliver-api/.tox/py36
          key: v1-dependencies-{{ checksum "enjoliver-api/tox.ini" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            cd enjoliver-api && tox

      - store_artifacts:
          path: test-reports
          destination: test-reports
